import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-ocean-freight-contract-rate-audit",
  "engine": "recovery",
  "title": "Ocean Freight Contract Rate Audit",
  "shortTitle": "Ocean Freight Contract Rate Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through ocean freight contract rate audit",
  "industry": "Ocean Transportation Spend Recovery",
  "uiPort": 4597,
  "apiPort": 5597,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Ocean Freight Contract Rate Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Carrier Billed Freight",
    "expectedLabel": "Contract-Supported Freight",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Ocean Freight Contract Rate Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("service-contract-library","OFC01","Service contract library","Execute service contract library using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed service contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Service contract library Reference","text","OFC01-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("origin-destination-rate-matrix","OFC02","Origin-destination rate matrix","Execute origin-destination rate matrix using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed origin-destination rate matrix decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Origin-destination rate matrix Reference","text","OFC02-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("container-and-equipment-registry","OFC03","Container and equipment registry","Execute container and equipment registry using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed container and equipment registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Container and equipment registry Reference","text","OFC03-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("booking-ingestion","OFC04","Booking ingestion","Execute booking ingestion using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed booking ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Booking ingestion Reference","text","OFC04-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("bill-of-lading-ingestion","OFC05","Bill-of-lading ingestion","Execute bill-of-lading ingestion using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed bill-of-lading ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Bill-of-lading ingestion Reference","text","OFC05-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("base-ocean-rate-reconstruction","OFC06","Base ocean rate reconstruction","Execute base ocean rate reconstruction using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed base ocean rate reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Base ocean rate reconstruction Reference","text","OFC06-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("bunker-adjustment-validation","OFC07","Bunker adjustment validation","Execute bunker adjustment validation using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed bunker adjustment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Bunker adjustment validation Reference","text","OFC07-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("peak-season-surcharge-audit","OFC08","Peak-season surcharge audit","Execute peak-season surcharge audit using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed peak-season surcharge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Peak-season surcharge audit Reference","text","OFC08-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("general-rate-increase-control","OFC09","General rate increase control","Execute general rate increase control using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed general rate increase control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","General rate increase control Reference","text","OFC09-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("mqc-tracking","OFC10","MQC tracking","Execute mqc tracking using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed mqc tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","MQC tracking Reference","text","OFC10-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("origin-charge-audit","OFC11","Origin charge audit","Execute origin charge audit using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed origin charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Origin charge audit Reference","text","OFC11-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("destination-charge-audit","OFC12","Destination charge audit","Execute destination charge audit using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed destination charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Destination charge audit Reference","text","OFC12-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("currency-validation","OFC13","Currency validation","Execute currency validation using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed currency validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Currency validation Reference","text","OFC13-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("carrier-dispute-generation","OFC14","Carrier dispute generation","Execute carrier dispute generation using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed carrier dispute generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Carrier dispute generation Reference","text","OFC14-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]}),
feature("lane-and-equipment-analytics","OFC15","Lane and equipment analytics","Execute lane and equipment analytics using ocean service contracts, amendments, bookings, bills of lading, origin-destination rates, equipment, quantities, bunker indexes, surcharges, invoices, and credits.","Produce a governed lane and equipment analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Shipment Lane","text","Carrier / Shipment Lane · Standard Case"],["caseReference","Lane and equipment analytics Reference","text","OFC15-2026-001"],["billedAmount","Carrier Billed Freight","currency",531000],["supportedAmount","Contract-Supported Freight","currency",456660],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Service contract library case","Origin-destination rate matrix case","Container and equipment registry case","Booking ingestion case","Bill-of-lading ingestion case"]})
]);
